version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Release
- Debug
platform: Win32
install:
- cmd: |
    vcpkg install ms-gsl
    git submodule update --init --recursive
build:
  project: vc15/ipod_manager.sln
  parallel: true
  verbosity: normal
